baseURL = 'https://devncode.it/'
languageCode = 'it-IT'
theme = "poison"
pluralizelisttitles = false

[params]
brand = "Dev'n'Code"
description = "It works on my machine!"
dark_mode = true
menu = []
email_url = "mailto://marco.cotrufo@devncode.it"
github_url = "https://github.com/marcocot"
linkedin_url = "https://www.linkedin.com/in/marcocotrufo/"
rss_icon = true
rss_section = "posts"

[pagination]
pagerSize = 10

[taxonomies]
series = 'series'
tags = 'tags'

[sitemap]
changefreq = "monthly"
priority = 0.5
